# display
name: CustomCommands
description: 'The easiest and most feature packed custom commands plugin'
author: GuillaumeVDN
website: www.guillaumevdn.com
# techy
version: 4.0.2
api-version: 1.13
main: com.guillaumevdn.customcommands.CustomCommands
depend: [GCore]
# commands
commands:
  customcommands:
    aliases: [ccmd]
    description: 'Main command for CustomCommands'
# permissions
permissions:
  # (super)
  customcommands.*:
    default: op
    children:
      # customcommands.admin (mainly allow usage of admin commands)
      customcommands.admin:
        default: op
      # customcommands.edit
      customcommands.edit:
        default: op
